version: "3"
services:
  # kafka-test:
  #   image: python:2.7
  #   networks:
  #     - kfk-net
  #   depends_on:
  #     - kafka

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    networks:
      - kfk-net
    ports:
      - 2181:2181/tcp
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
  
  kafka:
    image: confluentinc/cp-kafka:latest
    networks:
      - kfk-net
    ports:
      - 9092:9092/tcp
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
    depends_on:
      - zookeeper

networks:
  kfk-net:
